blogs/urls.py
from django.conf.urls import url, patterns


urlpatterns = patterns("",
    url(r'^$', "blogs.views.blog_index", name="home"),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$', "blogs.views.blog_post_detail", name="blog_post"),
    url(r'^post/(?P<post_pk>\d+)/$', "blogs.views.blog_post_detail", name="blog_post_pk"),
    url(r'^(?P<section_slug>[-\w]+)/$', "blogs.views.blog_section_list", name="blog_section"),
)

practical_exam/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from django.contrib import admin

urlpatterns = patterns(
    "",
    url(r"^admin/", include(admin.site.urls)),
    url(r"", include("blogs.urls")),
    url(r'^blogs/contact_us/', "blogs.views.contact", name="contact_us"),
    url(r'^blogs/signup/$', "blogs.views.signup", name="signup"),
    url(r'^blogs/login/$', "blogs.views.login_view", name="login"),
    url(r'^blogs/logout/$', "blogs.views.logout_view", name="logout"), 
    url(r'^blogs/add_post/$', "blogs.views.add_post", name="add_post"),
    url(r'^blogs/blog_manage_post/$', "blogs.views.blog_manage_post", name="blog_manage_post"),
    url(r'^blogs/blog_update_post/(?P<post_pk>\d+)/$', "blogs.views.blog_update_post", name="blog_update_post"),
    url(r'^blogs/blog_delete_post/(?P<post_pk>\d+)/$', "blogs.views.blog_delete_post", name="blog_delete_post"),
)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
# -*- coding: utf8 -*-
import json
import urllib2

from datetime import datetime

from django.conf import settings
from django.core.exceptions import ImproperlyConfigured
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from django.contrib.sites.models import Site

try:
    import twitter
except ImportError:
    twitter = None

from blogs.managers import PostManager
from blogs.settings import MARKUP_CHOICES
from blogs.utils import can_tweet



class Section(models.Model):
    name = models.CharField(max_length=140)
    slug = models.SlugField()

    def __unicode__(self):
        return self.name


class Post(models.Model):
    section = models.ForeignKey(Section, related_name="posts")
    
    title = models.CharField(max_length=90)
    slug = models.SlugField()
    author = models.ForeignKey(User, related_name="posts")
    
    markup = models.CharField(max_length=25, choices=MARKUP_CHOICES)
    
    teaser_html = models.TextField(editable=False)
    content_html = models.TextField(editable=False)
    
    tweet_text = models.CharField(max_length=140, editable=False)
    
    created = models.DateTimeField(default=datetime.now, editable=False) # when first revision was created
    updated = models.DateTimeField(null=True, blank=True, editable=False) # when last revision was create (even if not published)
    published = models.DateTimeField(null=True, blank=True, editable=False) # when last published
    
    view_count = models.IntegerField(default=0, editable=False)

    def rev(self, rev_id):
        return self.revisions.get(pk=rev_id)
    
    def current(self):
        "the currently visible (latest published) revision"
        return self.revisions.exclude(published=None).order_by("-published")[0]
    
    def latest(self):
        "the latest modified (even if not published) revision"
        try:
            return self.revisions.order_by("-updated")[0]
        except IndexError:
            return None
    
    class Meta:
        ordering = ("-published",)
        get_latest_by = "published"
    
    objects = PostManager()
    
    def __unicode__(self):
        return self.title
    
    def as_tweet(self):
        if not self.tweet_text:
            current_site = Site.objects.get_current()
            api_url = "http://api.tr.im/api/trim_url.json"
            u = urllib2.urlopen("%s?url=http://%s%s" % (
                api_url,
                current_site.domain,
                self.get_absolute_url(),
            ))
            result = json.loads(u.read())
            self.tweet_text = u"%s %s — %s" % (
                settings.TWITTER_TWEET_PREFIX,
                self.title,
                result["url"],
            )
        return self.tweet_text
    
    def tweet(self):
        if can_tweet():
            account = twitter.Api(
                username = settings.TWITTER_USERNAME,
                password = settings.TWITTER_PASSWORD,
            )
            account.PostUpdate(self.as_tweet())
        else:
            raise ImproperlyConfigured("Unable to send tweet due to either "
                "missing python-twitter or required settings.")
    
    def save(self, **kwargs):
        self.updated_at = datetime.now()
        super(Post, self).save(**kwargs)
    
    def get_absolute_url(self):
        if self.published:
            name = "blog_post"
            kwargs = {
                "year": self.published.strftime("%Y"),
                "month": self.published.strftime("%m"),
                "day": self.published.strftime("%d"),
                "slug": self.slug,
            }
        else:
            name = "blog_post_pk"
            kwargs = {
                "post_pk": self.pk,
            }
        return reverse(name, kwargs=kwargs)
    
    def inc_views(self):
        self.view_count += 1
        self.save()
        self.current().inc_views()


class Revision(models.Model):
    
    post = models.ForeignKey(Post, related_name="revisions")
    
    title = models.CharField(max_length=90)
    teaser = models.TextField()
    
    content = models.TextField()
    
    author = models.ForeignKey(User, related_name="revisions")
    
    updated = models.DateTimeField(default=datetime.now)
    published = models.DateTimeField(null=True, blank=True)
    
    view_count = models.IntegerField(default=0, editable=False)
    
    def __unicode__(self):
        return 'Revision %s for %s' % (self.updated.strftime('%Y%m%d-%H%M'), self.post.slug)
    
    def inc_views(self):
        self.view_count += 1
        self.save()


class Image(models.Model):
    
    post = models.ForeignKey(Post, related_name="images")
    
    image_path = models.ImageField(upload_to="images/%Y/%m/%d")
    url = models.CharField(max_length=150, blank=True)
    
    timestamp = models.DateTimeField(default=datetime.now, editable=False)
    
    def __unicode__(self):
        if self.pk is not None:
            return "{{ %d }}" % self.pk
        else:
            return "deleted image"


class FeedHit(models.Model):
    
    request_data = models.TextField()
    created = models.DateTimeField(default=datetime.now)

class Contact(models.Model):
   
    subject = models.CharField(max_length = 30)
    message = models.TextField(max_length = 100)
    email = models.EmailField()
    
    def __unicode__(self):
        return self.subject 

class SignUp(models.Model):
    new = 'new'
    old = 'old'
    status_choices = (
        (new, 'new user'),
        (old, 'old user'),
    )

    male = 'male'
    female = 'female'
    gender_choices = (
        (male, 'male'),
        (female, 'female'),
    )

    membership_status = models.CharField(max_length = 3, choices = status_choices, default = new)
    firstname = models.CharField(max_length = 50)
    lastname = models.CharField(max_length = 50)
    gender = models.CharField(max_length = 1, choices = gender_choices, default = male)
    address = models.TextField()
    mobile_number = models.CharField(max_length = 11)
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)

blogs/views.py
from datetime import datetime

from django.contrib.sites.models import Site
from django.core.urlresolvers import reverse
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, render_to_response, get_object_or_404
from django.template import RequestContext
from django.template.loader import render_to_string
from django.utils import simplejson as json

from blogs.models import FeedHit, Post, Section
from blogs.settings import ALL_SECTION_NAME
from blogs.signals import post_viewed
from blogs.forms import ContactForm, SignUpForm, LoginForm, AdminPostForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.core.mail import send_mail


@login_required(login_url='/blogs/login/')
def blog_index(request):
    
    sections = Section.objects.all()
    posts = Post.objects.current()
    
    return render_to_response("blogs/blog_list.html", {
        "posts": posts,
        "sections": sections,
    }, context_instance=RequestContext(request))

@login_required(login_url='/blogs/login/')
def blog_section_list(request, section_slug):
    
    sections = Section.objects.all()
    section = get_object_or_404(Section, slug=section_slug)
    posts   = section.posts.all()
    return render_to_response("blogs/blog_section_list.html", {
        "section_slug": section_slug,
        "section_name": section.name,
        "posts": posts,
        "sections": sections,
    }, context_instance=RequestContext(request))

@login_required(login_url='/blogs/login/')
def blog_post_detail(request, **kwargs):
    
    sections = Section.objects.all()
    if "post_pk" in kwargs:
        if request.user.is_authenticated() and request.user.is_staff:
            queryset = Post.objects.all()
            post = get_object_or_404(queryset, pk=kwargs["post_pk"])
        else:
            raise Http404()
    else:
        queryset = Post.objects.current()
        queryset = queryset.filter(
            published__year = int(kwargs["year"]),
            published__month = int(kwargs["month"]),
            published__day = int(kwargs["day"]),
        )
        post = get_object_or_404(queryset, slug=kwargs["slug"])
        post_viewed.send(sender=post, post=post, request=request)
    
    return render_to_response("blogs/blog_post.html", {
        "post": post,
        "sections": sections,
    }, context_instance=RequestContext(request))

@login_required(login_url='/blogs/login/')
def serialize_request(request):
    data = {
        "path": request.path,
        "META": {
            "QUERY_STRING": request.META.get("QUERY_STRING"),
            "REMOTE_ADDR": request.META.get("REMOTE_ADDR"),
        }
    }
    for key in request.META:
        if key.startswith("HTTP"):
            data["META"][key] = request.META[key]
    return json.dumps(data)

@login_required(login_url='/blogs/login/')
def blog_feed(request, section=None):
    
    section = get_object_or_404(Section, slug=section)
    posts = Post.objects.filter(section=section)

    if section is None:
        section = Section.objects.values_list('name', flat=True).order_by('name')

    current_site = Site.objects.get_current()
    
    feed_title = "%s Blog: %s" % (current_site.name, section[0].upper() + section[1:])
    
    blog_url = "http://%s%s" % (current_site.domain, reverse("blog"))
    
    url_name, kwargs = "blog_feed", {"section": section}
    feed_url = "http://%s%s" % (current_site.domain, reverse(url_name, kwargs=kwargs))
    
    if posts:
        feed_updated = posts[0].published
    else:
        feed_updated = datetime(2009, 8, 1, 0, 0, 0)
    
    # create a feed hit
    hit = FeedHit()
    hit.request_data = serialize_request(request)
    hit.save()
    
    atom = render_to_string("blogs/atom_feed.xml", {
        "feed_id": feed_url,
        "feed_title": feed_title,
        "blog_url": blog_url,
        "feed_url": feed_url,
        "feed_updated": feed_updated,
        "entries": posts,
        "current_site": current_site,
    })
    return HttpResponse(atom, mimetype="application/atom+xml")

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            email = form.cleaned_data['email']
     
            send_mail(subject, message, email, ['jrvjaralve@addu.edu.ph'], fail_silently=True)
            
            
            return HttpResponseRedirect('/')
        else:
            ContactForm(request.POST)
    else:
        form = ContactForm()

    return render(request, 'blogs/blog_contact.html', { 'form': form,}) 

def signup(request):
    registered = False

    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            user.set_password(user.password)
            user.save()

            registered = True
        else:
            print form.errors
    else:
        form = SignUpForm()

    return render(request, 'blogs/signup.html', { 'form': form, 'registered':registered,})

def login_view(request):
    context = {}
    context['check_errors'] = False
     
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
     
            user = authenticate(username=username, password=password)
     
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect('/')
                else:
                    context['check_errors'] = True
                    pass
            else:
                context['check_errors'] = True
                pass
     
            return HttpResponseRedirect('/')
    else:
        form = LoginForm()
     
    return render(request, 'blogs/login.html', { 'form': form,})

def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

def add_post(request):
    if request.method == 'POST':
        form = AdminPostForm(request.POST)
        if form.is_valid():
            form.save()
        else:
            AdminPostForm(request.POST)
    else:
        form = AdminPostForm()

    return render(request, 'blogs/add_post.html', { 'form': form,}, context_instance=RequestContext(request))

def blog_manage_post(request):

    sections = Section.objects.all()
    posts = Post.objects.filter(author=request.user).filter()

    return render_to_response('blogs/blog_manage_post.html', { 'posts': posts, 'sections':sections,}, context_instance=RequestContext(request))


def blog_update_post(request,post_pk): 
    
    sections = Section.objects.all()
    post = Post.objects.get(pk=post_pk) 
    if request.method == 'POST': 
        update = AdminPostForm(request.POST) 

        if update.is_valid(): 
            update.save() 
            return HttpResponseRedirect('/')
        else: 
            AdminPostForm(request.POST) 

    else: 
        if post: 
            update = AdminPostForm(instance=post) 

        else: 
            update = AdminPostForm() 
     
    return render_to_response("blogs/blog_update_post.html", {'update':update,'post':post, 'sections':sections,}, context_instance=RequestContext(request)) 

def blog_delete_post(request,post_pk): 

    sections = Section.objects.all()
    post = Post.objects.get(pk=post_pk) 
    if post: 
        post.delete() 
    else: 
        pass 

    posts = Post.objects.current() 
    
    return render_to_response("blogs/blog_manage_post.html", {'posts':posts, 'sections':sections,}, context_instance=RequestContext(request)) 

practical_exam/templates/blogs/add_post.html
{% extends "site_base.html" %}

{% block body %}
{% block title %}<h2>Add Post Here!</h2>{% endblock %}
<form action="{% url 'add_post' %}" method="post" enctype="multipart/form-data">
{% csrf_token %}
{{ form.as_p }}
<b><input type="submit" value="Add Post"/></b>

{% endblock %}

practical_exam/templates/blogs/blog_base.html
{% extends "site_base.html" %}

{% block body_class %}blog{% endblock %}


{% block body %}
    <div class="row blog-container">
        <div class="col-md-3 sidebar">
            {% block sidebar %}
                <b>Username:</b> {{ user.username }}</br>
                <b>Email:</b> {{ user.email }} </br>
                <b>Name:</b> {{ user.first_name }} {{ user.last_name }} </br></br>
                <form action= "{% url 'add_post' %}" method="post">
                {% csrf_token %}
                <b><input type="submit" value="Add Post"/></b>
                </form>
                <form action= "{% url 'blog_manage_post' %}" method="post">
                {% csrf_token %}
                <b><input type="submit" value="Manage Post"/></b>
                </form>
                
                <h1>
                    <a href="#">About the blog</a>
                </h1>
                <p class="lead">
                    This is where you can list your bio, add links
                    etc., by editing the <code>blogs/blog_base.html</code>
                    template.
            {% endblock %}
        </div>
        <div class="col-md-8 blog-content">
            {% block content %}{% endblock %}
        </div>
    </div>
{% endblock %}

practical_exam/templates/blogs/blog_contact.html
{% extends "blogs/blog_base.html" %}

{% block body %}
{% block title %}<h2>Contact Us</h2>{% endblock %}
<form action="{% url 'contact_us' %}" method="post">
{% csrf_token %}
{{ form.as_p}}
<input type="submit" value="Submit">
</form>

{% endblock %}

practical_exam/templates/blogs/blog_list.html
{% extends "blogs/blog_base.html" %}

{% block head_title %}{{ SITE_NAME }}{% endblock %}

{% block content %}
    {% if posts %}
        <div class="post-list">
            {% for post in posts %}
                <div class="post">
                    <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                    {% include "blogs/dateline.html" %}
                    <div class="teaser">{{ post.teaser_html|safe }}</div>
                    <p class="more"><a href="{{ post.get_absolute_url }}" class="post-link">read more...</a></p>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No blog posts have been published.</p>
    {% endif %}
{% endblock %}

practical_exam/templates/blogs/blog_manage_post.html
{% extends "blogs/blog_base.html" %}

{% block head_title %}{{ SITE_NAME }}{% endblock %}

{% block content %}
    {% if posts %}
        <div class="post-list">
            {% for post in posts %}
                <div class="post">
                    <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                    {% include "blogs/dateline.html" %}
                    <div class="teaser">{{ post.teaser_html|safe }}</div>
                    <p class="more"><a href="{{ post.get_absolute_url }}" class="post-link">read more...</a></p>
                    <a href="/blogs/blog_update_post/{{ post.id }}/"> 
                    <button>Update Post</button></a> 
                    <a href="/blogs/blog_delete_post/{{ post.id }}/"> 
                    <button>Delete Post</button></a>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No blog posts have been published.</p>
    {% endif %}
{% endblock %}

practical_exam/templates/blogs/blog_post.html
{% extends "blogs/blog_base.html" %}

{% block head_title %}{{ post.title }} &mdash; {{ SITE_NAME }}{% endblock %}

{% block extra_head %}
    <meta name="description" content="{{ post.teaser_html|striptags }}">
    <meta name="og:title" content="{{ post.title }}">
    <meta name="og:description" content="{{ post.teaser_html|striptags }}">
{% endblock %}

{% block content %}
    <div class="post-detail">
        <div class="post">
            <h1>{{ post.title }}</h1>
            {% include "blogs/dateline_stale.html" %}

            <div class="teaser">{{ post.teaser_html|safe }}</div>

            <div class="content">{{ post.content_html|safe }}</div>

            <div class="twitter-button">
                <a href="https://twitter.com/share" class="twitter-share-button" data-via="">Tweet</a>
                <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
            </div>
        </div>
    </div>
{% endblock %}

practical_exam/templates/blogs/blog_section_list.html
{% extends "blogs/blog_base.html" %}


{% block head_title %}{{ SITE_NAME }} ({{ section_name }}){% endblock %}

{% block content %}
    {% if posts %}
        <div class="post-list">
            {% for post in posts %}
                <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                {% include "blogs/dateline.html" %}
                <div class="teaser">{{ post.teaser_html|safe }}</div>
                <p class="more"><a href="{{ post.get_absolute_url }}" class="post-link">read more...</a></p>
            {% endfor %}
        </div>
    {% else %}
        <p>No blog posts have been published in this section.</p>
    {% endif %}
{% endblock %}

practical_exam/templates/blogs/blog_update_post.html
{% extends "site_base.html" %} 

{% block body %} 
{% block title%} Update Post Here! {% endblock%} 
    <div class="row blog-container"> 
        <div class="col-md-3 sidebar"> 
            {% block sidebar %} 
                <form id ="up_form" action="/blogs/blog_update_post/{{ post.id }}/" method="post" enctype='multipart/form-data'> 
                {% csrf_token %} 
                {{ update.as_p }} 
                <input type="submit" value="Save Post"/> 
            {% endblock %} 
        </div> 
        <div class="col-md-8 blog-content"> 
            {% block content %}{% endblock %} 
        </div> 
    </div> 
{% endblock %}

practical_exam/templates/blogs/dateline.html
<p class="post_dateline">
    <span class="date">{% if post.published %}{{ post.published|date:"jS F Y" }}{% else %}Not published yet{% endif %}</span>
    <br />
    by <span class="author"><a href="http://twitter.com/{{ post.author.username }}" title="@{{ post.author.username }}">{{ post.author.get_full_name }}</a></span> in
    <a href="{% url "blog_section" post.section.slug %}"><span class="section">{{ post.get_section_display|capfirst }}</span></a>
</p>

practical_exam/templates/blogs/dateline_stale.html
<p class="post_dateline">
    {% if not post.stale %}
        <span class="date">{% if post.published %}{{ post.published|date:"jS F Y" }}{% else %}Not published yet{% endif %}</span>
        <br />
    {% endif %}
    by <span class="author"><a href="http://twitter.com/{{ post.author.username }}" title="@{{ post.author.username }}">{{ post.author.get_full_name }}</a></span> in
    <a href="{% url "blog_section" post.section.slug %}"><span class="section">{{ post.get_section_display|capfirst }}</span></a>
</p>

practical_exam/templates/blogs/login.html
{% extends "site_base.html" %}

{% block body %}
{% block title %}<h2>Login Here!</h2>{% endblock %}
{% if forms.errors %}
<i>Invalid username or password. Please try again</i>
{% endif %}

<form action="{% url 'login' %}" method="post">
{% csrf_token %}
<table>
    <tr>
        <td>{{ form.username.label_tag }}</td>
        <td>{{ form.username }}</td>
    </tr>
    <tr>
        <td>{{ form.password.label_tag }}</td>
        <td>{{ form.password }}</td>
    </tr>
</table>
<input type="submit" value="Submit" />
<input type="hidden" name ="next" value="{{ next }}"/>
</form>
<h4><a href="{% url 'signup' %}">Sign Up Now!</a></h4> {% endblock %}
        

practical_exam/templates/blogs/signup.html
{% extends "site_base.html" %}

{% block body %}
{% block title %}<h2>Sign Up here!</h2>{% endblock %}

{% if registered %}
	{% csrf_token %}
	You have been registered! 
	<a href="/blogs/login/"> Login Now.</a>
{% else %}
	<form action= "/blogs/signup/" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
	<input type="submit" value="Submit"/>
	</form>
{% endif %}

{% endblock %}